name: xmpp_stone

description: "Xmpp Stone is lightweight XMPP client library written completely in Dart."

version: 0.4.4-dev.7

homepage: https://vukoye.github.io

environment:
  sdk: '>=2.12.0 <4.0.0'

#dependencies:
#  path: ^1.4.1
dependencies:
  xml: ^6.5.0
  cryptoutils: ^0.5.0
  crypto: ^3.0.5
  synchronized: ^3.2.0
  tuple: ^2.0.2
  unorm_dart: ^0.3.0
  image: ^4.2.0
  quiver: ^3.2.2 #hash code generator
  console: ^4.1.0 #for example
  intl: ^0.19.0
  collection: ^1.18.0
  universal_io: ^2.2.2
  web_socket_channel: ^3.0.1

dev_dependencies:
  test: ^1.25.2
  mockito: ^5.4.4
